# Generated by Django 2.2 on 2021-05-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20210530_2156'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ideas',
            field=models.ManyToManyField(related_name='users', to='ideas.Idea'),
        ),
    ]
