# Generated by Django 2.2 on 2021-06-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ideas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='settings.MEDIA_ROOT/user_images/default_avatar.jpg', upload_to='avatars'),
        ),
    ]
