# Generated by Django 2.2 on 2021-06-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='user_images/default_avatar.jpg', upload_to='avatars'),
        ),
    ]
