# Generated by Django 2.2 on 2021-06-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210609_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatars/default_avatar.jpg', upload_to='avatars'),
        ),
    ]
