# Generated by Django 2.2 on 2021-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ideas', '0002_idea_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ideas', models.ManyToManyField(related_name='likes', to='ideas.Idea')),
                ('users', models.ManyToManyField(related_name='likes', to='users.User')),
            ],
        ),
    ]
