# Generated by Django 2.2 on 2021-05-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20210530_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
