# Generated by Django 2.2 on 2021-05-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ideas', to='users.User'),
        ),
    ]
